name: Update Daily Quote

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Daily Quote
        run: |
         curl -s https://api.quotable.io/random?tags=technology | jq -r '.content + " - " + .author' > quote.txt

      - name: Update README
        run: |
          sed -i '/<!-- QUOTE-START -->/,/<!-- QUOTE-END -->/c\<!-- QUOTE-START -->\n\n'"$(cat quote.txt)"'\n\n<!-- QUOTE-END -->' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main  # Ensure the latest changes are pulled
          git add quote.txt README.md  # Explicitly track quote.txt
          git commit -m "Updated daily quote" || echo "No changes to commit"
          git push
