name: Update Daily Quote

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Daily Quote
      run: |
        curl -s https://api.quotable.io/random?tags=technology | jq -r '.content + " - " + .author' | tee quote.txt

    - name: Debug Quote Output
      run: cat quote.txt  # Print the quote in GitHub Actions logs

    - name: Update README
      run: |
        sed -i '/<!--QUOTE_START-->/, /<!--QUOTE_END-->/c\<!--QUOTE_START-->\n'"$(cat quote.txt)"'\n<!--QUOTE_END-->' README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Updated daily quote"
        git pull --rebase
        git push
